import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import { authOptions } from "../api/auth/[...nextauth]/route";
import "../globals.css";
import Image from "next/image";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChartLine, faFileLines, faRightFromBracket } from "@fortawesome/free-solid-svg-icons";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen">
          <aside className="bg-blue-100 w-48 p-4">
            <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
              <Image
                src={session.user.image}
                alt="avatar"
                width={256}
                height={256}
              />
            </div>
            <nav className="inline-flex mx-auto flex-col text-center mt-8 gap-6">
              <Link href="/account" className="flex gap-4">
                <FontAwesomeIcon
                  fixedWidth={true}
                  icon={faFileLines}
                  className="w-6 h-6 text-gray-600"
                />
                <span>My Page</span>
              </Link>
              <Link href="/analytics" className="flex gap-4">
              <FontAwesomeIcon
                icon={faChartLine}
                className="w-6 h-6 text-gray-600"
              />
                <span>Analytics</span>
              </Link>
              <button className="flex gap-4">
                <FontAwesomeIcon
                  icon={faRightFromBracket}
                  className="h-6 w-6 text-gray-600"
                />
                <span>Logout</span>
              </button>
            </nav>
          </aside>
          <div className="max-w-4xl mx-auto p-6">{children}</div>
        </main>
      </body>
    </html>
  );
}
